CA1-MVCApp/Controllers/PersonController.cs
using CA1_MVCApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CA1_MVCApp.Controllers
{
    public class PersonController : Controller
    {
        // GET: Display list of contacts
        public ActionResult Contacts()
        {
            var plist = MockDB.getContacts();
            return View(plist);
        }

        // Send SMS from Contacts screen: passing phone number to another action
        [HttpPost]
        public ActionResult SendText(string PhoneNumber)
        {
            return RedirectToAction("Index", "Home", new { number=PhoneNumber });
        }

        
    }
}

CA1-MVCApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Andrey Kolchin</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("MVC SMS Application", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
               
                    <li>@Html.ActionLink("Contacts", "Contacts", "Person")</li>
                </ul>
                @*@Html.Partial("_LoginPartial")*@
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            
                <p>&copy; @DateTime.Now.Year - Andrey Kolchin</p>
            
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>